orbs: # declare what orbs we are going to use
    node: circleci/node@5.0.3 # the node orb provides common node-related configuration
    codecov: codecov/codecov@3.2.3

version: 2.1 # using 2.1 provides access to orbs and other features

executors:
    node-executor:
        docker:
            - image: circleci/node:17.0.1 # Specify the Node.js version you need

jobs:
    test:
        executor: node-executor
        steps:
            - checkout # Check out the code from your repository

            - run:
                  name: Install dependencies
                  command: npm install

            - run:
                  name: Run tests
                  command: npm test -- --coverage

            - codecov/upload

workflows:
    version: 2
    test:
        jobs:
            - test
